// ══════════════════════════════════════════════════════════════
//  英语学习题库  subject_english.js
//  ★ 添加题目：在文件末尾 QB_ENGLISH 数组中追加
// ══════════════════════════════════════════════════════════════

window.QB_ENGLISH = [

// ────── 词汇 ──────
{c:'词汇', q:'"eloquent"的正确含义是？',
  o:['令人不安的','口才好的，雄辩的','勤奋刻苦的','令人愉悦的'], a:1,
  e:'"eloquent"意为口才好的、雄辩的。例：She is an eloquent speaker.（她是一位善于雄辩的演讲者。）同根词：eloquence（n.口才）'},

{c:'词汇', q:'"Despite"在句中的正确用法是？',
  o:['Despite of the rain, we went out.','Despite the rain, we went out.','Despite that it rained, we went out.','Despite of that it rained, we went out.'], a:1,
  e:'"despite"是介词，后接名词/代词/动名词，不用"of"。正确：Despite the rain, we went out.（尽管下雨，我们还是出去了。）区分：in spite of（同despite）；although/though后接从句。'},

{c:'词汇', q:'以下哪组词为近义词对？',
  o:['ancient（古老的）& contemporary（当代的）','abundant（丰富的）& scarce（稀缺的）','ambiguous（模糊的）& vague（含糊的）','optimistic（乐观的）& pessimistic（悲观的）'], a:2,
  e:'"ambiguous"和"vague"都表示不明确、含糊的，是近义词。其余三组均为反义词对。'},

{c:'词汇', q:'"procrastinate"的意思是？',
  o:['提前完成任务','拖延，推迟行动','积极主动行动','深思熟虑决策'], a:1,
  e:'"procrastinate"意为拖延。例：Stop procrastinating and start studying!（别拖延了，开始学习！）同义词：delay, postpone, put off。'},

{c:'词汇', q:'填空：The project is still _____ construction.',
  o:['on','in','under','at'], a:2,
  e:'"under construction"固定搭配，意为"在建设中/施工中"。类似：under pressure（压力下）、under investigation（调查中）、under control（控制中）。'},

{c:'词汇', q:'"The scientist made a significant _____ in cancer research." 填入？',
  o:['breakdown（崩溃）','breakthrough（突破）','breakup（分裂）','setback（挫折）'], a:1,
  e:'"breakthrough"指重大突破，固定搭配：make a breakthrough（取得突破）。例：a significant breakthrough in cancer research（癌症研究的重大突破）。'},

{c:'词汇', q:'下列哪个词表示"值得称赞的"？',
  o:['notorious（臭名昭著的）','praiseworthy / commendable（值得称赞的）','controversial（有争议的）','dreadful（可怕的）'], a:1,
  e:'"praiseworthy"和"commendable"都意为值得称赞的，是表扬某人时的高级词汇。反义：blameworthy（应受谴责的）。'},

// ────── 语法 ──────
{c:'语法', q:'下列哪个句子语法正确？',
  o:['Neither the students nor the teacher are wrong.','Neither the students nor the teacher is wrong.','Neither the students nor the teacher were wrong.','Neither the students or the teacher is wrong.'], a:1,
  e:'"neither...nor..."连接两个主语时，谓语动词与距离最近的主语一致（就近原则）。最近主语"the teacher"是单数，故用"is"。'},

{c:'语法', q:'选出正确的虚拟语气句子：',
  o:['If I were you, I will study harder.','If I was you, I would study harder.','If I were you, I would study harder.','If I am you, I would study harder.'], a:2,
  e:'与现在事实相反的虚拟语气：if从句用过去式（be动词一律用were），主句用"would/could + 动词原形"。正确：If I were you, I would study harder.'},

{c:'语法', q:'"Having finished the report, _____ went home." 主语应是？',
  o:['the report','it','he/she（完成报告的人）','they（the reports）'], a:2,
  e:'分词短语作状语时，其逻辑主语必须与主句主语一致。"Having finished the report"的逻辑主语是完成报告的人（he/she），不能是report（报告不能完成自己）。此类错误叫"悬垂分词"。'},

{c:'语法', q:'"It is important that every student _____ the rules." 正确形式？',
  o:['follows','follow','followed','is following'], a:1,
  e:'"It is important/necessary/essential that..."后接虚拟语气，从句谓语用"should+原形"或直接用原形（美式）。故填"follow"（动词原形）。'},

{c:'语法', q:'下列关于冠词用法，哪句正确？',
  o:['She is best student in the class.','She is a best student in class.','She is the best student in the class.','She is the best student in a class.'], a:2,
  e:'形容词最高级前一般加定冠词"the"，"in the class"表特定范围。正确：She is the best student in the class.'},

// ────── 出国备考 ──────
{c:'出国', q:'雅思（IELTS）写作Task 2字数要求是？',
  o:['至少150词','至少250词','至少300词','至少200词'], a:1,
  e:'IELTS写作：Task 2（议论文/说明文）至少250词，建议260-290词；Task 1（图表/流程图）至少150词。时间分配：Task 1约20分钟，Task 2约40分钟。'},

{c:'出国', q:'托福（TOEFL iBT）阅读题型不包括？',
  o:['Factual Information（事实信息题）','Inference（推断题）','Vocabulary（词汇题）','Error Correction（改错题）'], a:3,
  e:'托福阅读题型：事实信息题、否定事实题、词汇题、代词指代题、修辞目的题、句子简化题、推断题、文本插入题、小结/分类题。无"改错题"——那是SAT写作部分的题型。'},

{c:'出国', q:'"cover letter"在求职/申请中是指？',
  o:['简历（CV/Resume）','求职信/自荐信','成绩单','推荐信'], a:1,
  e:'"cover letter"（或covering letter）是申请工作/学校时随简历提交的求职信/自荐信，介绍申请动机和优势。区分：CV/Resume（简历）、Transcript（成绩单）、Letter of Recommendation（推荐信）、Personal Statement（个人陈述）。'},

{c:'出国', q:'GRE词汇中，"laconic"的反义词最可能是？',
  o:['silent（沉默的）','verbose（冗长啰嗦的）','eloquent（雄辩的）','articulate（表达清晰的）'], a:1,
  e:'"laconic"意为言简意赅的，反义词是"verbose/wordy（冗长啰嗦的）"。GRE常考反义词：laconic↔verbose, frugal↔prodigal, reticent↔voluble。'},

{c:'出国', q:'雅思写作"Coherence and Cohesion"（连贯与衔接）主要指？',
  o:['词汇的高级程度','语法多样性','段落逻辑清晰，正确使用连接词使文章流畅','句子长度变化'], a:2,
  e:'雅思写作四项评分：①Task Achievement（任务完成度）；②Coherence and Cohesion（连贯与衔接，逻辑结构和连接词）；③Lexical Resource（词汇多样性）；④Grammatical Range and Accuracy（语法准确性）。'},

{c:'出国', q:'以下哪个是申请文书（PS）中应避免的开头？',
  o:['Furthermore, this experience...','Ever since I was a child, I always wanted to...','This pivotal moment shaped my perspective...','I am drawn to this program because...'], a:1,
  e:'"Ever since I was a child..."是申请文书的典型陈词滥调（cliché）开头，招生官已读腻。建议用具体的场景、数据或事件开头，更有画面感和独特性。好的PS应当具体、独特、有故事感。'},

// ────── 阅读理解 ──────
{c:'阅读', q:'"The author implies that..." 此类题型考查的是？',
  o:['文章主旨大意','作者写作目的','作者未明说但暗示的意思（推断）','文章具体事实信息'], a:2,
  e:'"imply"（暗示）题型是推断题，需根据上下文推断作者未明说的含义。解题技巧：排除绝对化选项（never/always/only）；正确答案通常是原文的转述而非原词照搬。'},

{c:'阅读', q:'英文段落的主旨句（topic sentence）通常位于？',
  o:['段落最后一句','段落第二句','段落开头第一句','段落中间某句'], a:2,
  e:'英文议论文/说明文中，主旨句通常位于段落开头。结构：主旨句→支撑论据→举例说明→（总结句）。阅读时先看每段首句，可快速把握文章结构。'},

{c:'阅读', q:'英语阅读中遇到生词，最好的处理方式是？',
  o:['立即查字典','直接跳过不读','根据上下文（context clues）推断词义','放弃这道题'], a:2,
  e:'遇到生词：①根据上下文推断词义（利用context clues）；②分析构词法（前缀/后缀/词根）；③借助同义词/反义词判断。这是阅读理解最重要的技能之一，考试中不能查字典。'},

// ══ 在此下方添加新题目 ══
// {c:'分类', q:'题目', o:['A','B','C','D'], a:0, e:'解析'},
// ══════════════════════════════════════════════════════════════
//  英语旅游交际题库  适配原subject_english.js格式
//  总计250题 覆盖出国旅游全场景 可直接复制追加到QB_ENGLISH数组
// ══════════════════════════════════════════════════════════════
// ────── 机场入境（30题） ──────
{c:'机场入境', q:'入境时海关问"What is the purpose of your visit?"，旅游目的最标准回答是？',
  o:['I am here for traveling and sightseeing.','I am here to find a job.','I am here to study.','I am here for business.'], a:0,
  e:'旅游入境标准回答，清晰说明观光目的。其他选项对应求职、留学、商务场景，错误表述可能导致入境受阻。'},
{c:'机场入境', q:'值机时想要靠窗的座位，正确表达是？',
  o:['Can I have a window seat, please?','Can I have an aisle seat, please?','Can I have a back seat, please?','Can I have a front seat, please?'], a:0,
  e:'window seat 靠窗座位；aisle seat 靠过道座位，是值机时高频核心表达。例：Can I have a window seat for this flight?'},
{c:'机场入境', q:'"boarding pass"在机场场景中的含义是？',
  o:['机票','登机牌','行李牌','护照'], a:1,
  e:'boarding pass 登机牌，是登机、过安检的必备凭证；ticket 机票；luggage tag 行李牌；passport 护照。'},
{c:'机场入境', q:'托运行李时，工作人员问"Do you have any checked baggage?"，你只有随身背包，正确回答是？',
  o:['Yes, I have two suitcases.','No, I only have carry-on luggage.','No, I don\'t have a bag.','Yes, this is my baggage.'], a:1,
  e:'checked baggage 托运行李；carry-on luggage 随身行李，是机场高频词汇。该回答清晰说明无托运行李，仅带随身物品。'},
{c:'机场入境', q:'"What is your final destination?"的正确含义是？',
  o:['你的出发地是哪里？','你的最终目的地是哪里？','你打算待多久？','你的航班号是多少？'], a:1,
  e:'final destination 最终目的地，是入境、值机时的高频问句，需准确回答目的地城市名。'},
{c:'机场入境', q:'入境时被问"How long will you be staying in this country?"，你计划待14天，正确回答是？',
  o:['I will stay for 14 days.','I have 14 days off.','I will leave after 14 days.','I stay 14 days here.'], a:0,
  e:'该问句是入境必问问题，标准回答用"will stay for + 时长"，清晰说明停留时长，需与酒店订单、返程机票时间一致。'},
{c:'机场入境', q:'"excess baggage"的含义是？',
  o:['丢失的行李','超重行李','随身行李','托运行李'], a:1,
  e:'excess baggage 超重行李，机场高频词汇。例：You have to pay extra for excess baggage.（超重行李需要额外付费）'},
{c:'机场入境', q:'转机时想问"下一程航班的登机口在哪里？"，正确表达是？',
  o:['Where is the gate for my connecting flight?','Where is the ticket office?','Where is the baggage claim?','Where is the security check?'], a:0,
  e:'connecting flight 中转/衔接航班；gate 登机口，是转机场景核心表达。'},
{c:'机场入境', q:'"baggage claim"在机场场景中指的是？',
  o:['值机柜台','行李提取处','安检口','登机口'], a:1,
  e:'baggage claim / luggage claim 均指行李提取处，是落地后取托运行李的核心区域。'},
{c:'机场入境', q:'入境填写入境卡时，"country of residence"的含义是？',
  o:['国籍','居住国','出发国','目的地国'], a:1,
  e:'country of residence 居住国，通常填写你长期居住的国家；nationality 国籍，注意两个表达的区分，避免填错入境卡。'},
{c:'机场入境', q:'过安检时，工作人员说"Please take out your laptop."，意思是？',
  o:['请拿出你的手机','请拿出你的笔记本电脑','请脱下你的外套','请拿出你的液体物品'], a:1,
  e:'laptop 笔记本电脑，国际航班安检通常要求单独取出电脑过机，是高频安检指令。'},
{c:'机场入境', q:'"departure gate"的含义是？',
  o:['到达口','登机口','出发大厅','值机柜台'], a:1,
  e:'departure gate 登机口；arrival gate 到达口；check-in counter 值机柜台，机场核心词汇。'},
{c:'机场入境', q:'航班延误时，想问"这个航班什么时候起飞？"，正确表达是？',
  o:['When will this flight take off?','When will this flight land?','When will this flight arrive?','When will this flight cancel?'], a:0,
  e:'take off 起飞；land 降落，是航班场景核心动词短语。例：When will the flight to London take off?'},
{c:'机场入境', q:'入境时被问"Where will you be staying during your visit?"，正确回答是？',
  o:['I will stay at the Hilton Hotel in downtown.','I will travel around the country.','I will stay with my friend.','I will go to many cities.'], a:0,
  e:'该问题需提供具体住宿地址/酒店名称，与酒店预订单一致，是入境核查的核心问题，模糊回答可能被进一步盘问。'},
{c:'机场入境', q:'"duty-free shop"的含义是？',
  o:['便利店','免税店','特产店','超市'], a:1,
  e:'duty-free shop 免税店，国际出发/到达区的核心购物场所，duty-free 意为"免税的"。'},
{c:'机场入境', q:'托运行李丢失，想表达"我的行李找不到了"，正确说法是？',
  o:['I can\'t find my checked baggage.','I lost my passport.','My bag is stolen.','I left my bag on the plane.'], a:0,
  e:'行李丢失第一时间到机场失物招领处用该句说明情况，工作人员会引导你填写行李丢失申报单。'},
{c:'机场入境', q:'"transit visa"的含义是？',
  o:['旅游签证','商务签证','过境签证','学生签证'], a:2,
  e:'transit visa 过境签证，指在中转国转机时需要的签证，出行前需确认中转国是否需要过境签，避免无法登机。'},
{c:'机场入境', q:'值机时想问"这个航班的行李额度是多少？"，正确表达是？',
  o:['What is the baggage allowance for this flight?','How much is the excess baggage fee?','How many bags can I take?','What is the weight of my bag?'], a:0,
  e:'baggage allowance 行李额度，是值机时高频问句，包含托运行李的重量、件数限制。'},
{c:'机场入境', q:'"immigration counter"指的是？',
  o:['值机柜台','入境边检柜台','海关柜台','失物招领处'], a:1,
  e:'immigration counter 入境边检柜台，是落地后办理入境手续、盖章的地方，是入境的必经环节。'},
{c:'机场入境', q:'飞机上想索要一条毯子，正确表达是？',
  o:['Can I have a blanket, please?','Can I have a pillow, please?','Can I have a drink, please?','Can I have a meal, please?'], a:0,
  e:'blanket 毯子；pillow 枕头，是长途航班上的高频需求表达，用Can I have...please?句式礼貌得体。'},
{c:'机场入境', q:'"customs declaration"的含义是？',
  o:['入境卡','海关申报单','登机牌','行李票'], a:1,
  e:'customs declaration form 海关申报单，入境时携带超限额现金、贵重物品、需申报的物品时，必须填写申报。'},
{c:'机场入境', q:'转机时间紧张，想问"我能赶上我的中转航班吗？"，正确表达是？',
  o:['Will I make my connecting flight?','Can I change my flight?','Where is my next flight?','When does my next flight leave?'], a:0,
  e:'make the flight 是固定口语表达，意为"赶上航班"，是转机赶时间时的高频问句。'},
{c:'机场入境', q:'"estimated time of arrival (ETA)"的含义是？',
  o:['预计起飞时间','预计到达时间','实际起飞时间','航班延误时间'], a:1,
  e:'ETA=estimated time of arrival 预计到达时间；ETD=estimated time of departure 预计起飞时间，是航班信息核心缩写。'},
{c:'机场入境', q:'入境时被问"Do you have anything to declare?"，你没有需要申报的物品，正确回答是？',
  o:['No, nothing to declare.','Yes, I have some gifts.','I don\'t know what to declare.','I have nothing in my bag.'], a:0,
  e:'该句是海关入境必问问题，意为"你有需要申报的物品吗？"，无申报物品用该标准回答即可快速通关。'},
{c:'机场入境', q:'"carry-on luggage"的含义是？',
  o:['托运行李','随身行李','超重行李','丢失行李'], a:1,
  e:'carry-on luggage / hand luggage 均指随身行李，是机场高频核心词汇，需区分checked baggage（托运行李）。'},
{c:'机场入境', q:'想在机场兑换当地货币，正确问句是？',
  o:['Where is the currency exchange office?','Where is the bank?','Where is the ATM?','Where can I buy things?'], a:0,
  e:'currency exchange office 货币兑换处，机场内均设有该网点，可兑换当地货币，出行前可提前确认汇率。'},
{c:'机场入境', q:'"boarding time"的含义是？',
  o:['起飞时间','登机时间','值机时间','降落时间'], a:1,
  e:'boarding time 登机时间，通常打印在登机牌上，一般航班起飞前15-30分钟停止登机，需留意该时间。'},
{c:'机场入境', q:'飞机上想换座位，想问"这个座位有人吗？"，正确表达是？',
  o:['Is this seat taken?','Can I sit here?','Is this seat empty?','Who sits here?'], a:0,
  e:'Is this seat taken? 是英语中询问座位是否有人的最标准、最礼貌的口语表达，适用于飞机、餐厅、公共交通等多个场景。'},
{c:'机场入境', q:'"security check"的含义是？',
  o:['值机','安检','入境检查','海关检查'], a:1,
  e:'security check 安全检查，简称安检，是登机前的必经环节，是机场高频核心词汇。'},
// ────── 交通出行（25题） ──────
{c:'交通出行', q:'打车时想告诉司机"请去市中心"，正确表达是？',
  o:['Please take me to the city center.','Please drive to the countryside.','Please stop here.','Please go to the airport.'], a:0,
  e:'打车核心句式"Please take me to + 目的地"，是全球通用的打车表达，清晰准确。'},
{c:'交通出行', q:'"How much is the fare to the hotel?"中fare的含义是？',
  o:['距离','时间','车费','油费'], a:2,
  e:'fare 特指公共交通、出租车的车费，是交通场景高频核心词。例：The bus fare is 2 dollars.'},
{c:'交通出行', q:'坐公交时想问"这趟车到火车站吗？"，正确表达是？',
  o:['Does this bus go to the railway station?','Is this the railway station?','Where is the railway station?','When will we get to the railway station?'], a:0,
  e:'公交场景高频问句，用Does this bus go to...? 确认线路是否到达目的地，避免坐错车。'},
{c:'交通出行', q:'"one-way ticket"的含义是？',
  o:['单程票','往返票','学生票','团体票'], a:0,
  e:'one-way ticket 单程票；round-trip ticket / return ticket 往返票，是购票时核心区分词汇。'},
{c:'交通出行', q:'坐地铁时想问"去博物馆要在哪一站换乘？"，正确表达是？',
  o:['Which stop do I need to transfer to get to the museum?','Where is the museum station?','Which line goes to the museum?','When does the subway arrive?'], a:0,
  e:'transfer 换乘，是地铁/公交场景核心动词。例：You need to transfer at Central Station.'},
{c:'交通出行', q:'打车到达目的地后，想问"总共多少钱？"，正确表达是？',
  o:['How much is it in total?','How much is per kilometer?','Can I pay by card?','Do you have change?'], a:0,
  e:'in total 总计，是结账时高频短语，适用于打车、餐饮、购物等多个旅游场景。'},
{c:'交通出行', q:'"rush hour"的含义是？',
  o:['高峰时段','空闲时段','发车时间','到达时间'], a:0,
  e:'rush hour 交通高峰时段，也就是早晚高峰，出行前避开该时段可避免堵车，是旅游出行高频词汇。'},
{c:'交通出行', q:'租车时，"full to full"的行业惯例是指？',
  o:['满油取车，满油还车','满油取车，空油还车','空油取车，满油还车','空油取车，空油还车'], a:0,
  e:'full to full 是国际租车最通用的规则，指取车时油箱是满的，还车时也需要加满，否则会收取高额加油服务费。'},
{c:'交通出行', q:'坐火车时想问"这趟车的站台是哪个？"，正确表达是？',
  o:['Which platform is for this train?','Where is the train station?','When does the train leave?','Where can I buy a train ticket?'], a:0,
  e:'platform 站台，是火车站场景核心词汇，欧美火车站站台号通常会在发车前10-20分钟更新，需留意广播和屏幕。'},
{c:'交通出行', q:'"traffic jam"的含义是？',
  o:['交通信号灯','交通规则','交通堵塞','交通事故'], a:2,
  e:'traffic jam 交通堵塞，口语中也说traffic congestion，是出行时高频词汇。例：We were stuck in a traffic jam for an hour.'},
{c:'交通出行', q:'打车时想让司机"请开慢一点"，正确表达是？',
  o:['Please drive slowly.','Please speed up.','Please stop the car.','Please turn around.'], a:0,
  e:'drive slowly 开慢一点；speed up 加速，是打车时控制车速的核心表达，礼貌且清晰。'},
{c:'交通出行', q:'"valid for 3 days"在交通票中是指？',
  o:['3天内有效','3天后生效','仅限3天内使用一次','需要3天前购买'], a:0,
  e:'valid 有效的，是票务场景核心词。旅游城市的通票、公交卡通常会标注valid for X days，指有效期为X天。'},
{c:'交通出行', q:'坐公交时想下车，想问"下一站是市中心吗？"，正确表达是？',
  o:['Is the next stop the city center?','Where is the city center?','Does this bus stop at the city center?','When will we arrive at the city center?'], a:0,
  e:'next stop 下一站，是公交场景高频词汇，提前确认站点可避免坐过站。'},
{c:'交通出行', q:'"car rental"的含义是？',
  o:['出租车','汽车租赁','网约车','私家车'], a:1,
  e:'car rental 汽车租赁，也就是租车服务，是国外自由行高频场景，rental 意为"租赁的"。'},
{c:'交通出行', q:'网约车时想告诉司机"我在酒店正门等你"，正确表达是？',
  o:['I will wait for you at the main entrance of the hotel.','I am in the hotel lobby.','I will arrive at the hotel soon.','The hotel is on the main street.'], a:0,
  e:'main entrance 正门，是约定上车地点的核心表达，避免司机找不到位置，国外酒店通常有多个入口，需明确说明。'},
{c:'交通出行', q:'"underground / subway / metro"都指的是？',
  o:['火车','地铁','公交','高铁'], a:1,
  e:'三个词均指地铁：underground 多用于英国，subway 多用于美国，metro 多用于欧洲大陆，是全球通用的地铁表达。'},
{c:'交通出行', q:'坐火车时想问"这趟车有餐车吗？"，正确表达是？',
  o:['Does this train have a dining car?','Can I buy food on the train?','Is there a restaurant on the train?','Where can I eat on the train?'], a:0,
  e:'dining car 餐车，是火车场景核心词汇，长途火车通常会设有餐车，提供简餐和饮品。'},
{c:'交通出行', q:'"speed limit"的含义是？',
  o:['最低时速','最高时速','限速','平均时速'], a:2,
  e:'speed limit 限速，是自驾租车场景核心词汇，国外道路会明确标注speed limit，超速会面临高额罚款。'},
{c:'交通出行', q:'坐轮渡时想问"这趟船到对面的小岛吗？"，正确表达是？',
  o:['Does this ferry go to the island across the water?','Where is the ferry terminal?','When does the ferry leave?','How much is the ferry ticket?'], a:0,
  e:'ferry 轮渡/渡船，是海岛、沿海城市旅游高频交通工具，terminal 意为"码头/终点站"。'},
{c:'交通出行', q:'"no parking"的交通标识含义是？',
  o:['禁止停车','禁止通行','限速行驶','注意行人'], a:0,
  e:'no parking 禁止停车，是国外最常见的交通标识之一，违规停车会被拖车并收取高额罚款。'},
{c:'交通出行', q:'打车时想让司机"请打表"，正确表达是？',
  o:['Please use the meter.','Can you give me a discount?','How much is it to the airport?','Can you wait for me here?'], a:0,
  e:'meter 出租车计价器，use the meter 打表，是国外打车避免被宰的核心表达，尤其在旅游热门城市。'},
{c:'交通出行', q:'"bus stop"和"bus station"的区别是？',
  o:['bus stop是公交站点，bus station是公交总站','bus stop是公交总站，bus station是公交站点','两者没有区别','bus stop是长途车站，bus station是市内公交站'], a:0,
  e:'bus stop 指市内路边的公交站点；bus station 指大型公交总站/长途汽车站，是旅游出行必须区分的词汇，避免找错地点。'},
{c:'交通出行', q:'自驾时想问"最近的加油站在哪里？"，正确表达是？',
  o:['Where is the nearest gas station?','Where can I park my car?','Where is the car wash?','Where is the repair shop?'], a:0,
  e:'gas station（美）/ petrol station（英）均指加油站，nearest 最近的，是自驾场景高频问句。'},
{c:'交通出行', q:'"delay"在交通场景中的含义是？',
  o:['提前到达','准点到达','延误','取消'], a:2,
  e:'delay 延误，适用于航班、火车、公交等所有交通场景。例：The train has a 30-minute delay.'},
{c:'交通出行', q:'坐观光巴士时想问"这个票可以无限次上下车吗？"，正确表达是？',
  o:['Can I get on and off unlimited times with this ticket?','Is this ticket valid for one day?','Where can I buy this ticket?','How many stops does this bus have?'], a:0,
  e:'get on and off 上下车，unlimited times 无限次，是旅游城市观光巴士的核心权益，提前确认可合理规划行程。'},
// ────── 酒店住宿（25题） ──────
{c:'酒店住宿', q:'办理入住时，前台说"Do you have a reservation?"，你有提前预订，正确回答是？',
  o:['Yes, I have a reservation under the name Li Ming.','No, I don\'t have a room.','Yes, I want a single room.','No, I need to book a room.'], a:0,
  e:'reservation 预订，under the name + 姓名 是办理入住的标准表达，意为"以XX姓名预订的"，前台可快速查到你的订单。'},
{c:'酒店住宿', q:'"check-in"的含义是？',
  o:['办理入住','办理退房','预订房间','客房服务'], a:0,
  e:'check-in 办理入住；check-out 办理退房，是酒店场景最核心的两个词汇，酒店通常有固定的check-in和check-out时间。'},
{c:'酒店住宿', q:'想预订一间大床房，正确表达是？',
  o:['I would like to book a queen-size bed room.','I want a single room.','I need a twin room.','I want a suite.'], a:0,
  e:'queen-size bed room 大床房（欧美标准）；twin room 双床房（两张单人床），是预订酒店时最核心的房型区分词汇。'},
{c:'酒店住宿', q:'"room service"的含义是？',
  o:['客房服务','打扫服务','叫醒服务','洗衣服务'], a:0,
  e:'room service 客房服务，特指酒店提供的送餐、送物品到房间的服务，是酒店高频核心词汇。'},
{c:'酒店住宿', q:'入住后发现房间空调坏了，想表达"房间里的空调不能用了"，正确说法是？',
  o:['The air conditioner in my room doesn\'t work.','The heater in my room is broken.','The window in my room can\'t open.','The TV in my room has no signal.'], a:0,
  e:'doesn\'t work / is broken 均表示"坏了、无法使用"，是酒店报修的标准表达，air conditioner 空调，是高频报修场景。'},
{c:'酒店住宿', q:'"wake-up call"的含义是？',
  o:['叫醒服务','前台电话','紧急呼叫','客房电话'], a:0,
  e:'wake-up call 叫醒服务，是酒店基础服务之一，可向前台预约指定时间的电话叫醒，避免错过行程。'},
{c:'酒店住宿', q:'办理退房时，想问"我可以延迟退房到下午2点吗？"，正确表达是？',
  o:['Can I have a late check-out until 2 pm?','Can I stay in the room for another day?','When is the check-out time?','Can I keep the room key?'], a:0,
  e:'late check-out 延迟退房，是酒店场景高频需求，部分酒店会根据房态免费提供延迟退房，旺季可能会收取额外费用。'},
{c:'酒店住宿', q:'"twin room"的正确房型是？',
  o:['双床房（两张单人床）','大床房（一张双人床）','单人间','套房'], a:0,
  e:'twin room 双床房，是国外酒店标准房型，注意和double room区分：double room通常指带一张双人床的房间，预订时需明确避免订错。'},
{c:'酒店住宿', q:'想让酒店打扫房间，正确表达是？',
  o:['Can you clean my room, please?','Can you send me some towels?','Can you bring me more pillows?','Can you fix the TV in my room?'], a:0,
  e:'clean the room 打扫房间，是酒店基础服务，也可以说"Please make up my room"，是酒店行业通用表达。'},
{c:'酒店住宿', q:'"front desk / reception"的含义是？',
  o:['酒店前台/接待处','客房部','大堂','餐厅'], a:0,
  e:'front desk / reception 均指酒店前台，是办理入住、退房、咨询、报修的核心地点，是酒店场景最高频词汇。'},
{c:'酒店住宿', q:'入住时想问"酒店提供免费早餐吗？"，正确表达是？',
  o:['Is free breakfast included with the room?','Where is the breakfast restaurant?','What time is breakfast served?','Can I have breakfast in my room?'], a:0,
  e:'included 包含在内，是预订酒店时高频问句，确认房费是否包含早餐，避免额外消费。'},
{c:'酒店住宿', q:'"safe deposit box"在酒店中指的是？',
  o:['保险柜','行李寄存处','前台保险箱','储物柜'], a:0,
  e:'safe deposit box 保险柜，酒店房间内通常会配备，用于存放护照、现金、贵重物品，是旅游住宿保障财物安全的重要设施。'},
{c:'酒店住宿', q:'想问"早餐的供应时间是几点到几点？"，正确表达是？',
  o:['What time is breakfast served?','Where can I have breakfast?','Is breakfast free for guests?','Can I take breakfast away?'], a:0,
  e:'be served 是餐饮、酒店场景的标准表达，意为"供应、提供"，询问餐食供应时间的通用句式。'},
{c:'酒店住宿', q:'"luggage storage"的含义是？',
  o:['行李寄存','行李托运','行李丢失','行李打包'], a:0,
  e:'luggage storage 行李寄存，酒店通常为住客提供免费的行李寄存服务，退房后也可寄存，方便白天继续游玩。'},
{c:'酒店住宿', q:'房间里没有热水了，想向前台报修，正确表达是？',
  o:['There is no hot water in my room.','The water is too cold in my room.','The tap in my room is broken.','The bathroom is dirty.'], a:0,
  e:'no hot water 没有热水，是酒店高频报修场景，该表达清晰准确，前台会立即安排工程部维修。'},
{c:'酒店住宿', q:'"mini-bar"在酒店房间中指的是？',
  o:['迷你吧台/小冰箱（收费饮品零食）','迷你厨房','小型酒吧','咖啡机'], a:0,
  e:'mini-bar 指酒店房间内的小冰箱，里面的饮品、零食通常是收费的，退房时会统一结算，消费前需留意价格。'},
{c:'酒店住宿', q:'想问"酒店有免费Wi-Fi吗？"，正确表达是？',
  o:['Is there free Wi-Fi in the hotel?','What is the Wi-Fi password?','How to connect to the Wi-Fi?','Is the Wi-Fi fast in the hotel?'], a:0,
  e:'Wi-Fi 是全球通用的无线网络表达，该问句是入住酒店前/入住时的高频必问问题，部分酒店Wi-Fi可能收费。'},
{c:'酒店住宿', q:'"smoking room"和"non-smoking room"的区别是？',
  o:['smoking room是吸烟房，non-smoking room是无烟房','smoking room是无烟房，non-smoking room是吸烟房','两者没有区别','smoking room是带阳台的房间，non-smoking room是无阳台的房间'], a:0,
  e:'国外绝大多数酒店室内全面禁烟，预订和入住时必须明确要non-smoking room（无烟房），在无烟房吸烟会面临高额罚款。'},
{c:'酒店住宿', q:'想向前台多要几条毛巾，正确表达是？',
  o:['Can you send some extra towels to my room, please?','I need some new sheets.','Can you bring me more pillows?','My bathroom is out of toilet paper.'], a:0,
  e:'extra 额外的，towels 毛巾，是酒店高频需求，该表达礼貌得体，前台会安排客房服务员送到房间。'},
{c:'酒店住宿', q:'"check-out time"的含义是？',
  o:['退房时间','入住时间','预订时间','最晚到店时间'], a:0,
  e:'check-out time 退房时间，国外酒店通常标准退房时间是上午11点或中午12点，超时可能会收取额外房费。'},
{c:'酒店住宿', q:'入住时想问"酒店有游泳池吗？"，正确表达是？',
  o:['Does the hotel have a swimming pool?','Is the swimming pool open to guests?','What time does the swimming pool open?','Is the swimming pool free?'], a:0,
  e:'swimming pool 游泳池，是度假酒店高频咨询的设施，该问句是预订/入住时的标准表达。'},
{c:'酒店住宿', q:'"do not disturb"的标识含义是？',
  o:['请勿打扰','请打扫房间','紧急呼叫','禁止吸烟'], a:0,
  e:'do not disturb 请勿打扰，是酒店房间门后的标准标识，挂在门外后，客房服务员不会敲门打扫房间，保障住客隐私。'},
{c:'酒店住宿', q:'退房时前台问"Did you have anything from the mini-bar?"，意思是？',
  o:['您有没有消费房间迷你吧里的物品？','您有没有使用房间的保险箱？','您有没有带走房间的毛巾？','您有没有损坏房间的设施？'], a:0,
  e:'该句是退房时的标准核对问题，迷你吧消费是酒店退房时的常规结算项，需如实回答，避免账单错误。'},
{c:'酒店住宿', q:'"suite"在酒店房型中指的是？',
  o:['套房','单人间','双床房','大床房'], a:0,
  e:'suite 套房，通常指带客厅、卧室分离的房型，比普通房间空间更大、设施更全，价格也更高。'},
{c:'酒店住宿', q:'想问"酒店附近有地铁站吗？"，正确表达是？',
  o:['Is there a subway station near the hotel?','How can I get to the subway station?','How far is the subway station from the hotel?','Which subway line is near the hotel?'], a:0,
  e:'near the hotel 酒店附近，是入住时咨询周边交通的高频问句，方便规划出行路线。'},
// ────── 餐饮点餐（25题） ──────
{c:'餐饮点餐', q:'进入餐厅时，服务员说"How many people?"，正确回答是？',
  o:['A table for two, please.','We are two people.','We want to eat here.','We have a reservation.'], a:0,
  e:'A table for + 人数, please. 是进入餐厅的标准礼貌表达，意为"请给我们一张X人桌"，是全球餐厅通用句式。'},
{c:'餐饮点餐', q:'"menu"的含义是？',
  o:['菜单','账单','餐具','优惠券'], a:0,
  e:'menu 菜单，是餐厅场景最核心词汇，进入餐厅后可直接说"Can I have a menu, please?"索要菜单。'},
{c:'餐饮点餐', q:'想问"有中文菜单吗？"，正确表达是？',
  o:['Do you have a Chinese menu?','Can you speak Chinese?','I don\'t understand English.','Do you have a picture menu?'], a:0,
  e:'Chinese menu 中文菜单，旅游热门城市的餐厅大多会提供中文菜单，该问句可避免点餐时的语言障碍。'},
{c:'餐饮点餐', q:'"I am allergic to seafood."的核心含义是？',
  o:['我对海鲜过敏','我不喜欢吃海鲜','我不吃海鲜','海鲜太贵了'], a:0,
  e:'be allergic to 对...过敏，是餐饮场景最高频、最重要的表达，点餐时必须提前说明，避免食品安全问题。'},
{c:'餐饮点餐', q:'想点一杯不含酒精的饮料，正确表达是？',
  o:['Can I have a non-alcoholic drink, please?','I want a glass of wine.','Can I have a beer, please?','I want a cup of coffee.'], a:0,
  e:'non-alcoholic 不含酒精的，是点餐时核心区分词汇，国外很多饮料会标注含酒精/不含酒精，避免点错。'},
{c:'餐饮点餐', q:'"bill / check"在餐厅场景中的含义是？',
  o:['账单','菜单','餐具','小费'], a:0,
  e:'bill（英）/ check（美）均指餐厅账单，用餐结束后可说"Can I have the bill, please?"索要账单，是结账标准表达。'},
{c:'餐饮点餐', q:'想问"这道菜辣吗？"，正确表达是？',
  o:['Is this dish spicy?','Does this dish have pepper?','I don\'t like spicy food.','Can you make it less spicy?'], a:0,
  e:'spicy 辣的，是国外点餐高频问句，尤其是东南亚、墨西哥等菜系，很多菜品默认是辣的，提前确认可避免不适。'},
{c:'餐饮点餐', q:'"vegetarian"的含义是？',
  o:['素食主义者','肉食主义者','海鲜爱好者','乳糖不耐受者'], a:0,
  e:'vegetarian 素食者，点餐时说"I am a vegetarian."可明确告知服务员你不吃肉，餐厅会提供对应的素食选项。'},
{c:'餐饮点餐', q:'牛排点餐时，"medium"指的是几分熟？',
  o:['五分熟','三分熟','七分熟','全熟'], a:0,
  e:'牛排熟度标准：rare 一分熟，medium rare 三分熟，medium 五分熟，medium well 七分熟，well done 全熟，是西餐点餐核心知识点。'},
{c:'餐饮点餐', q:'想让菜品少放盐，正确表达是？',
  o:['Can you make it with less salt, please?','I don\'t like salty food.','This dish is too salty.','Can you add more salt?'], a:0,
  e:'less salt 少盐，是点餐时调整口味的标准表达，同理可用less sugar（少糖）、less oil（少油），适配不同饮食需求。'},
{c:'餐饮点餐', q:'"table for two"的含义是？',
  o:['两人桌','两张桌子','二楼的桌子','靠窗的桌子'], a:0,
  e:'table for + 人数，是餐厅预约、入座时的标准表达，例：I booked a table for four tonight.（我今晚预订了一张四人桌）'},
{c:'餐饮点餐', q:'想问"这里的招牌菜是什么？"，正确表达是？',
  o:['What is your signature dish?','What is the most expensive dish?','What do you recommend?','What is the cheapest dish here?'], a:0,
  e:'signature dish 招牌菜，是餐厅点餐高频问句，能快速吃到餐厅的特色菜品，比泛泛的推荐更精准。'},
{c:'餐饮点餐', q:'"tip"在餐厅场景中的含义是？',
  o:['小费','优惠券','折扣','服务费'], a:0,
  e:'tip 小费，是欧美餐饮场景的重要文化，美国餐厅通常需要支付账单金额15%-20%的小费，欧洲部分国家会将服务费包含在账单内。'},
{c:'餐饮点餐', q:'想打包剩下的食物，正确表达是？',
  o:['Can I get a doggy bag, please?','I want to take the food away.','Can you give me a box?','I don\'t want this food anymore.'], a:0,
  e:'doggy bag 是国外餐厅打包的标准口语表达，也可以说"Can I have a takeaway box?"，旅游时节约不浪费的通用表达。'},
{c:'餐饮点餐', q:'"lactose intolerant"的含义是？',
  o:['乳糖不耐受','坚果过敏','麸质过敏','海鲜过敏'], a:0,
  e:'lactose intolerant 乳糖不耐受，是点餐时重要的健康说明，告知服务员你不能喝牛奶、吃含乳制品的菜品，避免肠胃不适。'},
{c:'餐饮点餐', q:'想问"这个套餐里包含什么？"，正确表达是？',
  o:['What is included in this set meal?','How much is this set meal?','Is this set meal available now?','Can I change the side dish in this set?'], a:0,
  e:'set meal 套餐，是国外餐厅常见的点餐形式，该问句可提前确认套餐包含的菜品，避免点到不喜欢的食物。'},
{c:'餐饮点餐', q:'"appetizer"的含义是？',
  o:['前菜/开胃菜','主菜','甜品','汤品'], a:0,
  e:'appetizer / starter 均指前菜/开胃菜，西餐点餐顺序通常是：appetizer → soup → main course → dessert，是西餐点餐核心词汇。'},
{c:'餐饮点餐', q:'想预约餐厅，想问"你们今晚有空位吗？"，正确表达是？',
  o:['Do you have any available tables for tonight?','Can I book a table for tonight?','What time do you open tonight?','How many people can you seat?'], a:0,
  e:'available tables 空位/可用的桌子，是餐厅预约的高频问句，热门餐厅建议提前预约，避免到店后无位。'},
{c:'餐饮点餐', q:'"main course"的含义是？',
  o:['主菜','前菜','甜品','套餐'], a:0,
  e:'main course 主菜，是西餐的核心菜品，通常是肉类、海鲜类菜品，是点餐时的核心选择项。'},
{c:'餐饮点餐', q:'想问"营业到几点？"，正确表达是？',
  o:['What time do you close?','What time do you open?','Are you open now?','How long are you open today?'], a:0,
  e:'What time do you close? 是询问店铺打烊时间的标准通用表达，适用于餐厅、商店、景点等所有旅游场景，避免跑空。'},
{c:'餐饮点餐', q:'"gluten-free"的含义是？',
  o:['无麸质的','无糖的','无盐的','无脂肪的'], a:0,
  e:'gluten-free 无麸质的，是欧美餐饮高频标注，适合麸质过敏人群，点餐时说明需要gluten-free food，餐厅会提供对应的选项。'},
{c:'餐饮点餐', q:'用餐时想索要一杯水，正确表达是？',
  o:['Can I have a glass of water, please?','I want to drink something.','Do you have water?','Can I have a bottle of water?'], a:0,
  e:'该句是用餐时索要饮用水的标准礼貌表达，欧美多数餐厅会提供免费的自来水，瓶装水通常会收费。'},
{c:'餐饮点餐', q:'"side dish"的含义是？',
  o:['配菜/小食','主菜','前菜','甜品'], a:0,
  e:'side dish 配菜，通常搭配主菜一起点，常见的有薯条、沙拉、烤蔬菜等，是西餐点餐高频词汇。'},
{c:'餐饮点餐', q:'想问"可以分开结账吗？"，正确表达是？',
  o:['Can we have separate bills, please?','Can I pay by credit card?','Can we split the bill evenly?','Can I pay the bill now?'], a:0,
  e:'separate bills 分开结账，是和朋友一起用餐时的高频需求，也可以说split the bill，均为国外餐厅通用表达。'},
{c:'餐饮点餐', q:'"dessert"的含义是？',
  o:['甜品','饮料','汤品','咖啡'], a:0,
  e:'dessert 甜品，是西餐用餐的最后一个环节，常见的有蛋糕、冰淇淋、布丁等，是点餐时的核心词汇。'},
// ────── 购物消费（25题） ──────
{c:'购物消费', q:'进店后店员说"Can I help you?"，你只是随便看看，正确礼貌回答是？',
  o:['I\'m just looking around, thank you.','Yes, I want to buy something.','No, I don\'t need your help.','I want to try this on.'], a:0,
  e:'I\'m just looking around. 是国外购物时"随便看看"的标准礼貌表达，既回应了店员，又表达了暂时不需要帮助的需求，不会显得不礼貌。'},
{c:'购物消费', q:'"How much is this?"的含义是？',
  o:['这个多少钱？','这个有货吗？','这个可以打折吗？','这个有其他颜色吗？'], a:0,
  e:'这是购物场景最核心、最高频的问句，全球通用，询问商品价格的标准表达。'},
{c:'购物消费', q:'想问"这个可以打折吗？"，正确表达是？',
  o:['Is there any discount on this item?','How much is this?','Can I get a refund?','Is this on sale?'], a:0,
  e:'discount 折扣，是购物场景核心词汇。该句是询问折扣的标准礼貌表达，部分商场、免税店可凭护照享受游客折扣。'},
{c:'购物消费', q:'"on sale"的含义是？',
  o:['特价出售/打折中','在售中','预售中','缺货'], a:0,
  e:'on sale 是国外商场最高频的标识，意为"打折促销中"，区分for sale（待售，通常用于房产、二手物品）。'},
{c:'购物消费', q:'想试穿衣服，正确表达是？',
  o:['Can I try this on, please?','Where is the fitting room?','What size is this?','Do you have this in a medium?'], a:0,
  e:'try on 试穿，是服装购物核心短语，固定搭配try + 商品 + on，例：Can I try this dress on?'},
{c:'购物消费', q:'"fitting room / changing room"的含义是？',
  o:['试衣间','收银台','仓库','退换货柜台'], a:0,
  e:'fitting room（美）/ changing room（英）均指试衣间，是服装购物高频词汇，试穿前可问"Where is the fitting room?"。'},
{c:'购物消费', q:'想问"这个有小号吗？"，正确表达是？',
  o:['Do you have this in a small size?','What size is this?','Is this size small?','Can I get a smaller one?'], a:0,
  e:'服装尺码标准：small(S)小号，medium(M)中号，large(L)大号，XL加大号，是国外购物必须掌握的核心词汇。'},
{c:'购物消费', q:'"tax refund / tax free"的含义是？',
  o:['退税','免税','打折','优惠券'], a:0,
  e:'tax refund 退税，是境外旅游购物的核心福利，非本国游客在指定商店购物满一定金额，可在离境时申请退还消费税/增值税。'},
{c:'购物消费', q:'想问"你们接受信用卡支付吗？"，正确表达是？',
  o:['Do you accept credit cards?','Can I pay by cash?','Can I pay with Alipay?','What payment methods do you accept?'], a:0,
  e:'accept 接受，credit card 信用卡，是购物时确认支付方式的高频问句，国外绝大多数商场、餐厅都接受信用卡支付。'},
{c:'购物消费', q:'"out of stock"的含义是？',
  o:['缺货/无货','有货','在途','预售'], a:0,
  e:'out of stock 缺货，是购物场景高频词汇，反义是in stock（有货）。例：This item is out of stock.（这个商品没货了）'},
{c:'购物消费', q:'想买纪念品，想问"这个是当地产的吗？"，正确表达是？',
  o:['Is this locally made?','Is this handmade?','Is this authentic?','Is this a souvenir?'], a:0,
  e:'locally made 当地生产的，是买纪念品时的高频问句，能帮你买到真正的当地特色商品，避免买到进口的义乌小商品。'},
{c:'购物消费', q:'"receipt"的含义是？',
  o:['购物小票/收据','发票','账单','优惠券'], a:0,
  e:'receipt 购物小票，是购物退税、退换货的必备凭证，国外购物结账后一定要索要并保存好receipt。'},
{c:'购物消费', q:'想问"这个可以退换吗？"，正确表达是？',
  o:['Can I return or exchange this item?','Can I get a refund?','How long is the return period?','Is this item refundable?'], a:0,
  e:'return 退货，exchange 换货，是购物场景核心词汇，该句是确认退换货政策的标准表达，国外多数商场有30天退换货期。'},
{c:'购物消费', q:'"cashier / check-out counter"的含义是？',
  o:['收银台','服务台','试衣间','仓库'], a:0,
  e:'cashier / check-out counter 均指收银台，是购物结账的地方，选好商品后可说"I will pay at the cashier."。'},
{c:'购物消费', q:'想问"你们开门营业到几点？"，正确表达是？',
  o:['What time do you close?','What time do you open?','Are you open on weekends?','How long are you open today?'], a:0,
  e:'该句是询问店铺打烊时间的通用标准表达，适用于商场、超市、便利店等所有购物场景，避免跑空。'},
{c:'购物消费', q:'"handmade"的含义是？',
  o:['手工制作的','机器生产的','当地产的','进口的'], a:0,
  e:'handmade 手工制作的，是购买纪念品、手工艺品时的高频词汇，手工制品通常更有当地特色和纪念意义。'},
{c:'购物消费', q:'结账时想问"总价是多少？"，正确表达是？',
  o:['What is the total amount?','How much is each item?','Is there any discount?','Can I use a coupon?'], a:0,
  e:'total amount 总价，是结账时的高频问句，可核对账单金额是否正确，避免算错账。'},
{c:'购物消费', q:'"duty-free price"的含义是？',
  o:['免税价格','含税价格','折扣价格','原价'], a:0,
  e:'duty-free price 免税价格，是机场免税店、边境免税店的核心标识，免税商品免去了进口关税，价格通常比市内商场更低。'},
{c:'购物消费', q:'想问"这个有其他颜色吗？"，正确表达是？',
  o:['Do you have this in other colors?','What color is this?','I want a different color.','Is this color available?'], a:0,
  e:'other colors 其他颜色，是服装、箱包购物时的高频问句，可选择自己喜欢的颜色款式。'},
{c:'购物消费', q:'"warranty"的含义是？',
  o:['保修/质保','退换货','发票','收据'], a:0,
  e:'warranty 保修/质保，是购买电子产品、奢侈品时的核心词汇，例：This watch has a 2-year international warranty.（这块手表有2年全球联保）'},
{c:'购物消费', q:'想问"可以给我一个购物袋吗？"，正确表达是？',
  o:['Can I have a shopping bag, please?','Can I put these in a bag?','Do you have free bags?','Can I take this bag?'], a:0,
  e:'shopping bag 购物袋，国外很多商场的购物袋需要收费，该句是结账时的标准礼貌表达。'},
{c:'购物消费', q:'"original price"的含义是？',
  o:['原价','折扣价','含税价','免税价'], a:0,
  e:'original price 原价，打折商品通常会标注原价和现价，现价是current price / sale price，是购物时对比折扣力度的核心词汇。'},
{c:'购物消费', q:'买化妆品时想问"这个适合敏感肌吗？"，正确表达是？',
  o:['Is this suitable for sensitive skin?','Is this for dry skin?','Is this for oily skin?','Is this a moisturizer?'], a:0,
  e:'sensitive skin 敏感肌，是化妆品购物时的高频词汇，提前确认可避免护肤品过敏，保障皮肤安全。'},
{c:'购物消费', q:'"coupon / voucher"的含义是？',
  o:['优惠券/代金券','发票','收据','保修卡'], a:0,
  e:'coupon / voucher 均指优惠券、代金券，国外商场、超市经常会发放，结账时出示可享受折扣，是购物省钱的核心词汇。'},
{c:'购物消费', q:'想问"这个是正品吗？"，正确表达是？',
  o:['Is this authentic?','Is this fake?','Is this a good quality?','Is this original?'], a:0,
  e:'authentic 正品的、正宗的，是购买奢侈品、品牌商品时的高频问句，可确认商品是否为正品，避免买到假货。'},
// ────── 景点游玩（25题） ──────
{c:'景点游玩', q:'"ticket office / ticket booth"的含义是？',
  o:['售票处','入口','出口','游客中心'], a:0,
  e:'ticket office 售票处，是景点游玩的核心词汇，到达景点后首先要找售票处买票，也可以说ticket booth（小型售票亭）。'},
{c:'景点游玩', q:'想问"一张成人票多少钱？"，正确表达是？',
  o:['How much is an adult ticket?','How much is a child ticket?','Do you have a student discount?','What is the ticket price?'], a:0,
  e:'adult ticket 成人票，child ticket 儿童票，senior ticket 老人票，student ticket 学生票，是景点购票核心区分词汇。'},
{c:'景点游玩', q:'"student discount"的含义是？',
  o:['学生折扣','学生票','免费入场','团体优惠'], a:0,
  e:'student discount 学生折扣，国外很多博物馆、景点对持有效学生证的游客有折扣，甚至免费入场，出行时带上学生证可省钱。'},
{c:'景点游玩', q:'想问"这个景点的开放时间是几点？"，正确表达是？',
  o:['What are the opening hours of this attraction?','Is this attraction open today?','When does this attraction close?','Is this attraction open on weekends?'], a:0,
  e:'opening hours 开放时间，attraction 景点，是景点游玩最高频的问句，提前确认可避免景点闭馆跑空。'},
{c:'景点游玩', q:'"guided tour"的含义是？',
  o:['有导游的游览/跟团讲解','自由行','自助游览','语音导览'], a:0,
  e:'guided tour 带导游的讲解游览，很多博物馆、历史景点会提供定时的免费guided tour，能更深入了解景点的历史文化。'},
{c:'景点游玩', q:'想问"这里有中文语音导览吗？"，正确表达是？',
  o:['Do you have a Chinese audio guide?','Is there a Chinese speaking guide?','Can I get a Chinese map?','Do you have a Chinese brochure?'], a:0,
  e:'audio guide 语音导览，是博物馆、大型景点的标配，很多景点提供多语言语音导览，中文导览能解决语言障碍，更好地游览。'},
{c:'景点游玩', q:'"closed on Mondays"的标识含义是？',
  o:['每周一闭馆','每周一开放','周一提前关门','周一延迟开门'], a:0,
  e:'这是国外博物馆、景点最常见的闭馆标识，欧美绝大多数博物馆每周一闭馆，出行前一定要提前确认，避免跑空。'},
{c:'景点游玩', q:'想问"可以在这里拍照吗？"，正确表达是？',
  o:['Is photography allowed here?','Can I take a photo of you?','Where can I take photos?','Is flash photography allowed?'], a:0,
  e:'photography allowed 允许拍照，是景点游玩核心问句，很多博物馆的展品、宗教场所禁止拍照，提前确认可避免违规被罚款。'},
{c:'景点游玩', q:'"no flash photography"的标识含义是？',
  o:['禁止使用闪光灯拍照','禁止拍照','允许拍照','允许使用闪光灯拍照'], a:0,
  e:'这是博物馆、美术馆最常见的标识，闪光灯会对画作、文物造成损伤，即使允许拍照，也通常禁止使用闪光灯，违规会被罚款。'},
{c:'景点游玩', q:'想问"到山顶需要多长时间？"，正确表达是？',
  o:['How long does it take to get to the top of the mountain?','How far is it to the top of the mountain?','Is the trail to the top difficult?','Can I get to the top by cable car?'], a:0,
  e:'How long does it take to...? 是询问做某事需要多长时间的通用句式，登山、徒步景点高频使用，可合理规划体力和时间。'},
{c:'景点游玩', q:'"cable car"的含义是？',
  o:['缆车','索道','观光车','小火车'], a:0,
  e:'cable car 缆车，是高山、峡谷景点的常见交通工具，也可以说gondola，是景点游玩高频词汇。'},
{c:'景点游玩', q:'想问"最后一班观光车是几点？"，正确表达是？',
  o:['What time is the last sightseeing bus?','When does the first sightseeing bus leave?','How often does the sightseeing bus run?','Where is the sightseeing bus stop?'], a:0,
  e:'last bus 末班车，sightseeing bus 观光车，是大型景区高频问句，错过末班车可能会无法返回景区入口，一定要提前确认时间。'},
{c:'景点游玩', q:'"visitor center / tourist information center"的含义是？',
  o:['游客中心/旅游信息中心','售票处','入口','纪念品商店'], a:0,
  e:'visitor center 游客中心，是景点的核心服务区域，可领取地图、咨询游览路线、预约讲解、处理紧急情况，是旅游必去的地方。'},
{c:'景点游玩', q:'想问"有免费的景区地图吗？"，正确表达是？',
  o:['Do you have a free map of the attraction?','Where can I get a map?','Can I buy a map here?','Is there a digital map available?'], a:0,
  e:'free map 免费地图，绝大多数景点的游客中心都会提供免费的景区地图，标注游览路线、卫生间、休息区，是游览的必备品。'},
{c:'景点游玩', q:'"scenic spot / tourist attraction"的含义是？',
  o:['旅游景点/景区','游客中心','售票处','纪念品商店'], a:0,
  e:'scenic spot / tourist attraction 均指旅游景点、景区，是旅游场景最核心的基础词汇，全球通用。'},
{c:'景点游玩', q:'想问"这个景点适合带小孩去吗？"，正确表达是？',
  o:['Is this attraction suitable for children?','Can I bring my child here?','Is there a children\'s area?','Is this attraction child-friendly?'], a:0,
  e:'suitable for children 适合儿童，child-friendly 亲子友好的，是家庭出游时的高频问句，可提前确认景点是否适合带孩子游玩。'},
{c:'景点游玩', q:'"restroom / toilet"的含义是？',
  o:['卫生间/厕所','休息室','餐厅','休息区'], a:0,
  e:'restroom（美）/ toilet（英）均指卫生间，是旅游场景最高频的词汇，景区内可问"Where is the nearest restroom?"找最近的卫生间。'},
{c:'景点游玩', q:'想问"这里有轮椅通道吗？"，正确表达是？',
  o:['Is there wheelchair access here?','Can I bring a wheelchair here?','Is this attraction wheelchair-friendly?','Where can I rent a wheelchair?'], a:0,
  e:'wheelchair access 轮椅通道，wheelchair-friendly 无障碍友好的，是行动不便人士出游的高频问句，国外绝大多数景点都有无障碍设施。'},
{c:'景点游玩', q:'"souvenir shop"的含义是？',
  o:['纪念品商店','小卖部','超市','免税店'], a:0,
  e:'souvenir shop 纪念品商店，几乎所有景点出口处都会设有，可购买当地特色纪念品，是景点游玩高频词汇。'},
{c:'景点游玩', q:'想问"这个展览的讲解是几点开始？"，正确表达是？',
  o:['What time does the exhibition tour start?','How long is the exhibition?','Is the exhibition included in the ticket?','Where is the exhibition?'], a:0,
  e:'exhibition 展览，tour 讲解游览，是博物馆、美术馆场景高频问句，定时讲解能让你更深入了解展览内容。'},
{c:'景点游玩', q:'"national park"的含义是？',
  o:['国家公园','城市公园','森林公园','地质公园'], a:0,
  e:'national park 国家公园，是国外热门的旅游目的地，比如美国黄石国家公园，通常以自然风光为主，适合徒步、露营、观光。'},
{c:'景点游玩', q:'想问"可以在这里露营吗？"，正确表达是？',
  o:['Is camping allowed here?','Where can I camp?','Do I need a permit to camp?','Is there a campsite nearby?'], a:0,
  e:'camping allowed 允许露营，是国家公园、自然景区高频问句，很多自然区域露营需要提前申请许可，违规露营会被罚款。'},
{c:'景点游玩', q:'"hiking trail"的含义是？',
  o:['徒步路线/登山步道','观光车道','自行车道','缆车索道'], a:0,
  e:'hiking trail 徒步路线，是国家公园、自然景区核心词汇，国外徒步路线会标注难度等级和长度，可根据自身情况选择。'},
{c:'景点游玩', q:'想问"这个景点的最佳游览时间是多久？"，正确表达是？',
  o:['How long is the recommended visit for this attraction?','What is the best time to visit this attraction?','How long can I stay in this attraction?','When does this attraction open?'], a:0,
  e:'recommended visit 推荐游览时长，是景点游玩高频问句，可提前规划行程，合理安排每个景点的游览时间。'},
{c:'景点游玩', q:'"no entry"的标识含义是？',
  o:['禁止入内','禁止拍照','禁止吸烟','禁止停车'], a:0,
  e:'no entry 禁止入内，是景区、博物馆常见的标识，通常是未开放区域、工作人员区域、危险区域，切勿违规进入，避免发生危险。'},
// ────── 问路导航（20题） ──────
{c:'问路导航', q:'想问"最近的地铁站在哪里？"，正确表达是？',
  o:['Where is the nearest subway station?','How can I get to the subway station?','Which line goes to the city center?','Is the subway station far from here?'], a:0,
  e:'nearest 最近的，subway station 地铁站，是问路场景最高频的问句，全球通用，能快速找到交通站点。'},
{c:'问路导航', q:'"How can I get to the city center?"的含义是？',
  o:['我怎么去市中心？','市中心在哪里？','到市中心需要多长时间？','市中心离这里远吗？'], a:0,
  e:'这是问路场景最核心的通用句式，How can I get to + 目的地？，适用于任何地点的问路，全球通用。'},
{c:'问路导航', q:'想问"离这里远吗？"，正确表达是？',
  o:['Is it far from here?','How far is it from here?','How long does it take to get there?','Can I walk there?'], a:0,
  e:'far from here 离这里远，是问路时必问的问题，可判断是步行前往还是乘坐交通工具。'},
{c:'问路导航', q:'"go straight"的含义是？',
  o:['直走','左转','右转','掉头'], a:0,
  e:'go straight 直走，是指路场景最核心的基础词汇，搭配turn left（左转）、turn right（右转），就能听懂绝大多数的指路指引。'},
{c:'问路导航', q:'想问"我可以步行到那里吗？"，正确表达是？',
  o:['Can I walk there?','Is it within walking distance?','How long does it take to walk there?','Is it safe to walk there?'], a:0,
  e:'该句是问路时高频问句，可确认目的地是否在步行可达范围内，避免走冤枉路。'},
{c:'问路导航', q:'"on the left / on the right"的含义是？',
  o:['在左边/在右边','在里面/在外面','在前面/在后面','在楼上/在楼下'], a:0,
  e:'这是指路场景核心方位词，例：The hotel is on the left.（酒店就在左边），是听懂指路指引的必备词汇。'},
{c:'问路导航', q:'想问"过马路之后要左转吗？"，正确表达是？',
  o:['Do I turn left after crossing the road?','Where should I cross the road?','Do I cross the road here?','Should I turn left or right?'], a:0,
  e:'cross the road 过马路，turn left 左转，是问路时确认路线的高频问句，避免走错方向。'},
{c:'问路导航', q:'"traffic lights"的含义是？',
  o:['交通信号灯/红绿灯','十字路口','斑马线','立交桥'], a:0,
  e:'traffic lights 红绿灯，是指路场景高频地标词汇，例：Turn right at the traffic lights.（在红绿灯处右转），是国外指路最常用的地标。'},
{c:'问路导航', q:'想问"这个地址在哪里？"，正确表达是？',
  o:['Where is this address?','How can I get to this address?','Is this address near here?','What is near this address?'], a:0,
  e:'address 地址，是问路场景核心词汇，国外的地址通常有门牌号和街道名，拿着地址问路是最精准的方式。'},
{c:'问路导航', q:'"crossroads / intersection"的含义是？',
  o:['十字路口','斑马线','红绿灯','立交桥'], a:0,
  e:'crossroads / intersection 均指十字路口，是指路场景高频地标词汇，例：Go straight to the next crossroads.（直走到下一个十字路口）。'},
{c:'问路导航', q:'想问"附近有公共卫生间吗？"，正确表达是？',
  o:['Is there a public restroom nearby?','Where is the nearest toilet?','Can I use the restroom here?','Is the restroom free?'], a:0,
  e:'nearby 附近的，public restroom 公共卫生间，是旅游时最高频的问路需求，尤其在陌生的城市街道。'},
{c:'问路导航', q:'"opposite / across from"的含义是？',
  o:['在...对面','在...旁边','在...后面','在...前面'], a:0,
  e:'opposite / across from 均指"在...对面"，是指路场景核心方位词，例：The bank is opposite the hotel.（银行就在酒店对面）。'},
{c:'问路导航', q:'想问"到那里需要多长时间？"，正确表达是？',
  o:['How long does it take to get there?','How far is it from here?','Can I get there by bus?','What time does it open?'], a:0,
  e:'该句是问路时的高频必问问题，可根据时长规划出行方式和时间，避免耽误行程。'},
{c:'问路导航', q:'"next to / beside"的含义是？',
  o:['在...旁边/紧邻','在...对面','在...后面','在...前面'], a:0,
  e:'next to / beside 均指"在...旁边、紧邻"，是指路场景核心方位词，例：The supermarket is next to the station.（超市就在车站旁边）。'},
{c:'问路导航', q:'想问"我走错路了吗？"，正确表达是？',
  o:['Am I going the wrong way?','Is this the right way to the hotel?','Where am I now?','How can I get back on track?'], a:0,
  e:'wrong way 错误的路线，该句是导航失灵、迷路时的高频问句，当地人会给你正确的指引，避免越走越偏。'},
{c:'问路导航', q:'"landmark"的含义是？',
  o:['地标建筑','路牌','地图','导航'], a:0,
  e:'landmark 地标建筑，是问路时的核心词汇，当地人通常会用标志性的建筑给你指路，比如教堂、商场、高塔等，更容易找到位置。'},
{c:'问路导航', q:'想问"这趟公交到火车站吗？"，正确表达是？',
  o:['Does this bus go to the railway station?','Where is the bus stop to the railway station?','Which bus goes to the railway station?','How many stops to the railway station?'], a:0,
  e:'该句是坐公交时的高频问路问句，可提前确认线路是否正确，避免坐错车、坐反方向。'},
{c:'问路导航', q:'"one way street"的含义是？',
  o:['单行道','步行街','主干道','辅路'], a:0,
  e:'one way street 单行道，是自驾、问路时的高频词汇，国外很多市中心的街道是单行道，走错会面临罚款，也会绕远路。'},
{c:'问路导航', q:'想问"你能在地图上指给我看吗？"，正确表达是？',
  o:['Can you show me on the map, please?','Do you have a map?','Where is this on the map?','Can you draw me a map?'], a:0,
  e:'show me on the map 在地图上指给我看，是问路时的绝佳辅助，避免语言不通导致的理解偏差，能更精准地找到路线。'},
{c:'问路导航', q:'"U-turn"的含义是？',
  o:['掉头','左转','右转','倒车'], a:0,
  e:'U-turn 掉头，是自驾、指路场景高频词汇，国外很多道路禁止U-turn，会有"No U-turn"的标识，违规会被高额罚款。'},
// ────── 应急求助（20题） ──────
{c:'应急求助', q:'"Help!"的核心含义是？',
  o:['救命！','帮帮我！','走开！','小心！'], a:0,
  e:'Help! 是紧急情况最直接的呼救语，全球通用，遇到危险、紧急情况时大声喊，能快速吸引周围人的注意，获得帮助。'},
{c:'应急求助', q:'我的护照丢了，想表达"我的护照不见了"，正确说法是？',
  o:['I have lost my passport.','My passport is stolen.','I can\'t find my ID card.','I left my passport in the hotel.'], a:0,
  e:'lost 丢失，passport 护照，是境外旅游最重要的证件，丢失后第一时间用该句向当地警方报案，然后联系中国使领馆补办。'},
{c:'应急求助', q:'"police"的含义是？',
  o:['警察','医院','消防','救护车'], a:0,
  e:'police 警察，紧急情况可拨打当地报警电话，喊Police! 能快速获得帮助，全球通用。'},
{c:'应急求助', q:'我生病了，想表达"我需要医生"，正确说法是？',
  o:['I need a doctor.','I feel sick.','I have a headache.','I need to go to the hospital.'], a:0,
  e:'I need a doctor. 是生病时最直接的求助表达，酒店、餐厅、商场的工作人员会帮你联系医生或医院，避免病情加重。'},
{c:'应急求助', q:'"ambulance"的含义是？',
  o:['救护车','消防车','警车','急救车'], a:0,
  e:'ambulance 救护车，遇到严重受伤、突发重病时，拨打当地急救电话，喊Ambulance! 能快速获得急救帮助。'},
{c:'应急求助', q:'遇到紧急情况，想问"中国大使馆在哪里？"，正确表达是？',
  o:['Where is the Chinese Embassy?','How can I contact the Chinese Consulate?','I need help from the Chinese Embassy.','What is the phone number of the Chinese Embassy?'], a:0,
  e:'Chinese Embassy 中国大使馆，Chinese Consulate 中国领事馆，是境外遇到重大问题时的核心求助渠道，能提供领事保护和协助。'},
{c:'应急求助', q:'"I can\'t speak English very well. Can you speak Chinese?"的核心含义是？',
  o:['我英语不太好，你会说中文吗？','我不会说英语，你能帮我翻译吗？','我听不懂你说的话，请说慢一点','我需要一个中文翻译'], a:0,
  e:'该句是遇到问题、语言不通时的万能求助句，能快速筛选出会说中文的人，帮你解决问题，避免沟通障碍。'},
{c:'应急求助', q:'我的钱包被偷了，想表达"我的钱包被偷了"，正确说法是？',
  o:['My wallet was stolen.','I lost my wallet.','I can\'t find my wallet.','Someone took my wallet.'], a:0,
  e:'stolen 被偷，wallet 钱包，遇到盗窃事件第一时间用该句向警方报案，同时挂失银行卡和信用卡，避免财产损失。'},
{c:'应急求助', q:'"fire"的含义是？',
  o:['火/火灾','水','地震','洪水'], a:0,
  e:'fire 火灾，遇到火情时大声喊Fire! 能快速提醒周围的人，同时拨打当地火警电话，是紧急情况的核心呼救语。'},
{c:'应急求助', q:'我受伤了，想表达"我受伤了，需要帮助"，正确说法是？',
  o:['I\'m hurt. I need help.','I have a pain in my leg.','I fell down and hurt myself.','I need a bandage.'], a:0,
  e:'I\'m hurt. 我受伤了，是意外受伤时最直接的求助表达，周围的人会给你提供帮助，严重时会帮你叫救护车。'},
{c:'应急求助', q:'"emergency"的含义是？',
  o:['紧急情况/突发事件','安全','危险','帮助'], a:0,
  e:'emergency 紧急情况，是应急场景核心词汇，国外所有公共场所都有emergency exit（紧急出口）、emergency call（紧急电话）标识。'},
{c:'应急求助', q:'想问"最近的医院在哪里？"，正确表达是？',
  o:['Where is the nearest hospital?','I need to go to the hospital.','Is there a hospital nearby?','Can you take me to the hospital?'], a:0,
  e:'nearest hospital 最近的医院，是生病、受伤时的高频求助问句，能快速找到就医地点，及时治疗。'},
{c:'应急求助', q:'"emergency exit"的标识含义是？',
  o:['紧急出口','安全通道','禁止入内','紧急呼叫'], a:0,
  e:'emergency exit 紧急出口，是酒店、商场、机场、飞机等所有公共场所的必备标识，遇到火灾、突发事件时，从紧急出口疏散。'},
{c:'应急求助', q:'我和家人走散了，想表达"我找不到我的家人了"，正确说法是？',
  o:['I can\'t find my family.','I lost my child.','My family is missing.','Can you help me find my family?'], a:0,
  e:'该句是和家人走散时的求助表达，景区、商场的工作人员会帮你广播找人，同时调取监控，快速找到走散的家人。'},
{c:'应急求助', q:'"first aid kit"的含义是？',
  o:['急救包','药品','医院','救护车'], a:0,
  e:'first aid kit 急救包，里面有绷带、消毒水、创可贴等急救用品，轻微受伤时可先用急救包处理，酒店、景区、车上通常会配备。'},
{c:'应急求助', q:'我的手机丢了，想表达"我的手机不见了"，正确说法是？',
  o:['I have lost my phone.','My phone is broken.','I can\'t find my phone charger.','My phone has no signal.'], a:0,
  e:'lost my phone 手机丢失，是旅游时常见的突发情况，丢失后第一时间挂失手机号、冻结支付账户，避免财产损失，同时向警方报案。'},
{c:'应急求助', q:'"I\'m lost."的含义是？',
  o:['我迷路了。','我丢东西了。','我受伤了。','我生病了。'], a:0,
  e:'I\'m lost. 是迷路时最直接的求助表达，全球通用，当地人会给你指路，帮你回到正确的路线上。'},
{c:'应急求助', q:'想问"紧急电话是多少？"，正确表达是？',
  o:['What is the emergency number here?','Can you call the police for me?','I need to make an emergency call.','Where is the emergency phone?'], a:0,
  e:'emergency number 紧急电话，全球不同国家的紧急电话不同：美国911，欧洲112，日本110，出行前一定要提前确认当地的紧急电话。'},
{c:'应急求助', q:'"danger"的标识含义是？',
  o:['危险','安全','警告','禁止'], a:0,
  e:'danger 危险，是户外、景区、工地最常见的警示标识，看到该标识一定要远离，避免发生意外，保障自身安全。'},
{c:'应急求助', q:'我被困住了，想表达"请帮帮我，我被困住了"，正确说法是？',
  o:['Please help me, I\'m trapped.','Please help me, I\'m stuck.','I can\'t get out, please help me.','I\'m locked in, please help me.'], a:0,
  e:'trapped 被困住，stuck 被卡住，是电梯故障、被困在房间里、意外被困时的核心求助表达，能快速让周围的人了解你的处境，提供帮助。'},
// ────── 货币支付（20题） ──────
{c:'货币支付', q:'"currency exchange"的含义是？',
  o:['货币兑换','汇率','银行','ATM机'], a:0,
  e:'currency exchange 货币兑换，是境外旅游的核心场景，机场、市中心都有货币兑换点，可将人民币兑换成当地货币。'},
{c:'货币支付', q:'想问"今天的汇率是多少？"，正确表达是？',
  o:['What is the exchange rate today?','How much is the exchange fee?','Where can I exchange money?','Is there a better exchange rate?'], a:0,
  e:'exchange rate 汇率，是货币兑换时的核心词汇，汇率每天都会波动，兑换前一定要确认当天的汇率，避免被坑。'},
{c:'货币支付', q:'"exchange fee / commission"的含义是？',
  o:['手续费/佣金','汇率','兑换金额','税费'], a:0,
  e:'exchange fee 手续费，commission 佣金，是货币兑换时的核心费用，很多兑换点会用低汇率吸引你，然后收取高额手续费，兑换前一定要确认。'},
{c:'货币支付', q:'想问"这里的ATM机支持银联卡吗？"，正确表达是？',
  o:['Does the ATM here accept UnionPay cards?','Where is the nearest ATM?','Can I withdraw cash from the ATM?','Is there a service fee for ATM withdrawal?'], a:0,
  e:'UnionPay 银联，是中国的银行卡组织，全球绝大多数国家的ATM机都支持银联卡，可直接取出当地货币，是最方便的取现方式。'},
{c:'货币支付', q:'"cash"的含义是？',
  o:['现金','信用卡','银行卡','手机支付'], a:0,
  e:'cash 现金，是境外旅游必备的支付方式，很多小商店、菜市场、小费都只能用现金支付，出行前一定要兑换适量的当地现金。'},
{c:'货币支付', q:'想问"可以用支付宝支付吗？"，正确表达是？',
  o:['Do you accept Alipay?','Can I pay with WeChat Pay?','What payment methods do you accept?','Can I pay by mobile phone?'], a:0,
  e:'Alipay 支付宝，WeChat Pay 微信支付，在全球旅游热门城市的商场、免税店、餐厅都支持，汇率划算，没有手续费，是非常方便的支付方式。'},
{c:'货币支付', q:'"credit card"的含义是？',
  o:['信用卡','借记卡','预付卡','礼品卡'], a:0,
  e:'credit card 信用卡，是境外旅游最主流的支付方式，Visa和Mastercard是全球通用的信用卡组织，几乎所有商户都接受。'},
{c:'货币支付', q:'想问"取现的手续费是多少？"，正确表达是？',
  o:['What is the service fee for cash withdrawal?','How much cash can I withdraw at a time?','Is there a limit on cash withdrawal?','Can I withdraw cash with my debit card?'], a:0,
  e:'cash withdrawal 取现，service fee 手续费，是ATM取现时的核心问句，不同银行的手续费不同，出行前可提前了解发卡行的境外取现政策。'},
{c:'货币支付', q:'"local currency"的含义是？',
  o:['当地货币','人民币','美元','欧元'], a:0,
  e:'local currency 当地货币，是旅游场景核心词汇，例：I need to exchange some local currency.（我需要兑换一些当地货币）。'},
{c:'货币支付', q:'想问"这里可以刷芯片卡吗？"，正确表达是？',
  o:['Do you accept chip cards here?','Can I pay with a contactless card?','Is my card accepted here?','Can I swipe my card here?'], a:0,
  e:'chip card 芯片卡，是目前全球主流的银行卡类型，欧美绝大多数商户都只支持芯片卡，磁条卡可能无法使用，出行前一定要带芯片卡。'},
{c:'货币支付', q:'"contactless payment"的含义是？',
  o:['非接触式支付/闪付','手机支付','刷卡支付','现金支付'], a:0,
  e:'contactless payment 非接触式支付，也就是闪付，是欧美最主流的小额支付方式，银行卡、手机都支持，碰一下就能付款，非常方便。'},
{c:'货币支付', q:'想问"账单里包含服务费吗？"，正确表达是？',
  o:['Is service charge included in the bill?','Do I need to pay a tip?','How much is the service charge?','Can I pay the service charge by card?'], a:0,
  e:'service charge 服务费，欧洲很多餐厅、酒店会将服务费包含在账单里，就不需要额外支付小费了，提前确认可避免重复支付。'},
{c:'货币支付', q:'"VAT / value added tax"的含义是？',
  o:['增值税/消费税','服务费','关税','所得税'], a:0,
  e:'VAT 增值税，也就是消费税，欧洲国家的商品价格里通常都包含VAT，非欧盟游客购物满一定金额，可申请退还VAT，也就是退税。'},
{c:'货币支付', q:'想问"最低消费是多少？"，正确表达是？',
  o:['What is the minimum spend?','Is there a minimum charge?','How much do I need to spend?','Can I spend less than the minimum?'], a:0,
  e:'minimum spend / minimum charge 最低消费，是部分餐厅、酒吧、刷卡支付时的常见要求，提前确认可避免不必要的消费。'},
{c:'货币支付', q:'"receipt"的含义是？',
  o:['小票/收据','发票','账单','退税单'], a:0,
  e:'receipt 购物小票/收据，是支付后必须索要的凭证，退税、退换货、对账都需要用到，境外消费一定要保存好所有receipt。'},
{c:'货币支付', q:'想问"可以给我换一些零钱吗？"，正确表达是？',
  o:['Can you give me some change, please?','Do you have change for a 100 euro note?','Can I break this bill?','I need some coins for the bus.'], a:0,
  e:'change 零钱，是境外旅游高频需求，公交、小费、自动售货机都需要零钱，该句是兑换零钱的标准礼貌表达。'},
{c:'货币支付', q:'"traveler\'s check"的含义是？',
  o:['旅行支票','旅游保险','银行卡','信用卡'], a:0,
  e:'traveler\'s check 旅行支票，是一种安全的境外支付方式，丢失后可挂失补办，适合携带大额资金出行，不过现在使用的人越来越少，大多被信用卡取代。'},
{c:'货币支付', q:'想问"这个价格是含税的吗？"，正确表达是？',
  o:['Is this price including tax?','How much is the tax?','Is tax included in the bill?','Can I get a tax refund?'], a:0,
  e:'including tax 含税，是购物、餐饮时的高频问句，欧美很多商品标价是不含税的，结账时会额外加税，提前确认可避免预算超支。'},
{c:'货币支付', q:'"PIN code"的含义是？',
  o:['密码/支付密码','卡号','验证码','有效期'], a:0,
  e:'PIN code 支付密码，是境外刷卡、ATM取现时必须输入的密码，欧美芯片卡刷卡时都需要输入PIN码，出行前一定要记住银行卡的密码。'},
{c:'货币支付', q:'想问"退税的流程是什么？"，正确表达是？',
  o:['What is the tax refund process?','How much tax can I get back?','Where can I get the tax refund?','What documents do I need for tax refund?'], a:0,
  e:'tax refund process 退税流程，是境外购物的核心需求，购物时索要退税单，离境时在机场海关盖章，然后到退税柜台办理退税，可退现金或退到信用卡里。'},
// ────── 日常礼貌交际（35题） ──────
{c:'日常交际', q:'"Thank you very much."的最标准礼貌回应是？',
  o:['You\'re welcome.','No thanks.','It\'s okay.','Never mind.'], a:0,
  e:'You\'re welcome. 是回应感谢的最标准、最通用的礼貌表达，全球通用，适用于所有正式和非正式场景。'},
{c:'日常交际', q:'"Excuse me."的核心使用场景是？',
  o:['打扰一下/借过，用于引起别人注意、问路、借过','对不起，用于道歉','谢谢，用于表达感谢','再见，用于告别'], a:0,
  e:'Excuse me. 是境外旅游最高频的万能礼貌用语，问路、借过、打断别人、叫服务员都可以用，是必须掌握的第一句话。'},
{c:'日常交际', q:'不小心撞到别人，想道歉，正确表达是？',
  o:['I\'m sorry.','Excuse me.','Pardon me.','That\'s my fault.'], a:0,
  e:'I\'m sorry. 是道歉的最标准表达，不小心撞到别人、打扰到别人、做错事都可以用，是日常交际核心礼貌用语。'},
{c:'日常交际', q:'"Good morning."的适用场景是？',
  o:['早上到中午12点之间的问候','下午的问候','晚上的问候','睡前的问候'], a:0,
  e:'Good morning. 早上好，是上午见面的标准礼貌问候，酒店、餐厅、商店的工作人员都会和你说，回应也用Good morning.即可。'},
{c:'日常交际', q:'想问"你会说中文吗？"，正确表达是？',
  o:['Can you speak Chinese?','Do you understand Chinese?','Can you translate for me?','I can\'t speak English.'], a:0,
  e:'该句是境外旅游解决语言障碍的万能问句，遇到问题先问这句话，能快速找到会说中文的人，帮你解决问题。'},
{c:'日常交际', q:'"How are you?"的最标准礼貌回应是？',
  o:['I\'m fine, thank you. And you?','I\'m 25 years old.','I\'m from China.','I\'m traveling here.'], a:0,
  e:'How are you? 是英语中最常见的日常问候，意为"你好吗？"，标准回应是"I\'m fine, thank you. And you?"，礼貌又得体。'},
{c:'日常交际', q:'想让别人重复一遍刚才说的话，正确礼貌表达是？',
  o:['Pardon? / Could you say that again, please?','What?','I don\'t understand.','Speak Chinese.'], a:0,
  e:'Pardon? 是没听清别人说话时，最礼貌的请求重复的表达，也可以说"Could you speak more slowly, please?"（你能说慢一点吗？），解决听力障碍。'},
{c:'日常交际', q:'"See you later."的含义是？',
  o:['回头见/待会见','再见','明天见','晚上见'], a:0,
  e:'See you later. 是日常告别时的常用表达，意为"回头见"，适用于非正式的告别场景，比Goodbye.更轻松自然。'},
{c:'日常交际', q:'进入商店、餐厅，工作人员说"Hello!"，正确礼貌回应是？',
  o:['Hello! / Hi!','Thank you.','You\'re welcome.','Excuse me.'], a:0,
  e:'Hello! / Hi! 是最基础的问候语，别人和你打招呼时，用同样的问候回应即可，礼貌又简单，全球通用。'},
{c:'日常交际', q:'"Have a nice day!"的含义是？',
  o:['祝你度过美好的一天！','祝你玩得开心！','一路顺风！','祝你好运！'], a:0,
  e:'Have a nice day! 是欧美最常用的告别祝福语，结账、告别时工作人员都会和你说，回应也用"You too! / Have a nice day!"即可。'},
{c:'日常交际', q:'想问"这个用英语怎么说？"，正确表达是？',
  o:['How do you say this in English?','What is this?','Can you speak English?','What does this mean?'], a:0,
  e:'该句是学习英语、遇到不认识的物品时的万能问句，当地人会告诉你对应的英语单词，能快速积累旅游相关的词汇。'},
{c:'日常交际', q:'"No, thank you."的适用场景是？',
  o:['礼貌地拒绝别人的提议、推销、帮助','接受别人的帮助','道歉','感谢'], a:0,
  e:'No, thank you. 是礼貌拒绝的标准表达，店员推销、服务员问是否需要加东西、别人提供不需要的帮助时，用这句话拒绝，礼貌又不会得罪人。'},
{c:'日常交际', q:'"Yes, please."的适用场景是？',
  o:['礼貌地接受别人的提议、帮助、服务','拒绝别人的帮助','道歉','感谢'], a:0,
  e:'Yes, please. 是礼貌接受的标准表达，服务员问是否需要水、店员问是否需要帮助、别人提供帮助时，用这句话接受，礼貌又得体。'},
{c:'日常交际', q:'想问"你能帮我一个忙吗？"，正确礼貌表达是？',
  o:['Could you help me, please?','Can you help me?','Help me!','I need your help.'], a:0,
  e:'Could you help me, please? 是请求帮助的最礼貌、最通用的表达，比Can you help me?更委婉得体，适用于所有向陌生人求助的场景。'},
{c:'日常交际', q:'"What time is it now?"的含义是？',
  o:['现在几点了？','今天几号？','今天星期几？','现在是什么时候？'], a:0,
  e:'该句是询问时间的标准通用表达，旅游时经常需要问时间，避免错过航班、车次、预约，是日常交际高频问句。'},
{c:'日常交际', q:'别人和你说"I\'m sorry."，正确礼貌回应是？',
  o:['It\'s okay. / No problem.','You\'re welcome.','Thank you.','Never mind.'], a:0,
  e:'It\'s okay. / No problem. 是回应道歉的标准表达，意为"没关系"，适用于所有非正式场景，别人不小心撞到你、打扰到你时，用这句话回应，礼貌又大方。'},
{c:'日常交际', q:'"Where are you from?"的含义是？',
  o:['你来自哪里？','你要去哪里？','你现在在哪里？','你住在哪里？'], a:0,
  e:'该句是日常聊天最常见的问句，意为"你来自哪里？"，旅游时和当地人、其他游客聊天时经常会用到，回应可以说"I\'m from China."。'},
{c:'日常交际', q:'想表达"我来自中国"，正确表达是？',
  o:['I\'m from China.','I live in China.','I am Chinese.','I travel from China.'], a:0,
  e:'I\'m from China. 是介绍自己来自哪里的标准表达，入境、和当地人聊天、遇到问题时，这句话都能用到，是基础核心表达。'},
{c:'日常交际', q:'"Happy New Year!"的正确回应是？',
  o:['Happy New Year to you too!','Thank you.','You\'re welcome.','Same to you!'], a:0,
  e:'该句是新年祝福，回应可以用"Happy New Year to you too!"或者"Same to you!"，都是标准礼貌的回应方式，适用于节日祝福场景。'},
{c:'日常交际', q:'"What does this mean?"的含义是？',
  o:['这个是什么意思？','这个用英语怎么说？','这个是什么？','这个多少钱？'], a:0,
  e:'该句是遇到不认识的单词、标识、句子时的万能问句，能快速了解对方的意思，解决语言障碍，是旅游高频问句。'},
{c:'日常交际', q:'别人和你说"Happy birthday!"，正确回应是？',
  o:['Thank you very much!','Happy birthday!','You too!','No problem.'], a:0,
  e:'收到生日祝福时，标准的回应是感谢，用"Thank you very much!"即可，礼貌又得体。'},
{c:'日常交际', q:'"Could you speak more slowly, please?"的含义是？',
  o:['你能说慢一点吗？','你能再说一遍吗？','你能大声一点吗？','你能说中文吗？'], a:0,
  e:'该句是听不懂对方说话时的核心礼貌表达，当地人说话太快时，用这句话让对方放慢语速，能更好地理解对方的意思，解决听力障碍。'},
{c:'日常交际', q:'"Have a good trip!"的含义是？',
  o:['祝你旅途愉快！','一路顺风！','祝你玩得开心！','祝你度过美好的一天！'], a:0,
  e:'Have a good trip! 是对出行的人的标准祝福语，意为"祝你旅途愉快"，别人祝你旅途愉快时，回应用"Thank you!"即可。'},
{c:'日常交际', q:'想问"今天天气怎么样？"，正确表达是？',
  o:['What\'s the weather like today?','Is it raining today?','Is it cold today?','What temperature is it today?'], a:0,
  e:'该句是询问天气的标准通用表达，旅游时每天都需要了解天气，规划行程，是日常交际高频问句。'},
{c:'日常交际', q:'"I don\'t understand."的含义是？',
  o:['我听不懂/我不明白。','我不会说英语。','你能说中文吗？','你能再说一遍吗？'], a:0,
  e:'I don\'t understand. 是语言不通时的核心表达，直接告诉对方你听不懂，对方会换更简单的表达方式，或者找会说中文的人帮你，是旅游必备句子。'},
{c:'日常交际', q:'别人和你说"Thank you."，除了You\'re welcome，还可以用哪个礼貌回应？',
  o:['No problem. / My pleasure.','It\'s okay.','Never mind.','That\'s fine.'], a:0,
  e:'No problem. 是非正式场景最常用的回应感谢的表达，My pleasure. 是更正式、更礼貌的表达，意为"我的荣幸"，适用于服务场景。'},
{c:'日常交际', q:'"Excuse me, where is the nearest restroom?"的核心含义是？',
  o:['打扰一下，最近的卫生间在哪里？','打扰一下，最近的地铁站在哪里？','打扰一下，最近的医院在哪里？','打扰一下，最近的餐厅在哪里？'], a:0,
  e:'该句是旅游时最高频的日常问句，把restroom换成任何你想去的地点，就能变成对应的问路句子，是万能问路模板。'},
{c:'日常交际', q:'"Good night."的适用场景是？',
  o:['晚上睡觉前的告别/晚安问候','晚上见面的问候','下午的问候','早上的问候'], a:0,
  e:'Good night. 晚安，只适用于晚上睡觉前的告别，不能用于晚上见面的问候，晚上见面问候用Good evening.（晚上好），注意区分。'},
{c:'日常交际', q:'想问"你叫什么名字？"，正确礼貌表达是？',
  o:['What\'s your name?','May I have your name, please?','Who are you?','What is your name called?'], a:1,
  e:'May I have your name, please? 是询问对方名字的最礼貌、最正式的表达，比What\'s your name?更得体，适用于和陌生人、服务人员、正式场合的交流。'},
{c:'日常交际', q:'"I\'m Chinese."的含义是？',
  o:['我是中国人。','我来自中国。','我住在中国。','我会说中文。'], a:0,
  e:'I\'m Chinese. 是介绍自己国籍的标准表达，入境、和当地人聊天、遇到问题时，这句话都能用到，是基础核心表达。'},
{c:'日常交际', q:'别人和你说"Have a nice weekend!"，正确回应是？',
  o:['You too! / Have a nice weekend!','Thank you very much!','No problem.','You\'re welcome.'], a:0,
  e:'该句是周末祝福，意为"祝你周末愉快"，回应用"You too!"或者"Have a nice weekend!"即可，礼貌又自然。'},
{c:'日常交际', q:'"Is it okay if I sit here?"的含义是？',
  o:['我可以坐在这里吗？','这个座位有人吗？','这里可以坐吗？','你介意我坐在这里吗？'], a:0,
  e:'该句是询问是否可以坐在这里的礼貌表达，适用于餐厅、咖啡馆、公共交通等场景，比Is this seat taken?更委婉得体。'},
{c:'日常交际', q:'"I need a little help."的含义是？',
  o:['我需要一点帮助。','我需要很多帮助。','我不需要帮助。','你能帮我吗？'], a:0,
  e:'该句是请求帮助的委婉表达，比直接说Help me!更礼貌，适用于需要小帮助的场景，比如提行李、拍照、找路等。'},
{c:'日常交际', q:'"See you tomorrow."的含义是？',
  o:['明天见。','回头见。','再见。','晚上见。'], a:0,
  e:'See you tomorrow. 明天见，是约定好第二天见面时的告别表达，适用于酒店、导游、约好第二天见面的朋友等场景。'},
]; // end QB_ENGLISH

